const swaggerAutogen = require('swagger-autogen')();
const outputFile = './swagger_output.json'; // 輸出的文件名稱
const endpointsFiles = ['./app.js']; // 要指向的 API，通常使用 Express 直接指向到 app.js 就可以

const doc = {
  info: {
    version: "1.0.0",
    title: "FriendNet API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  schemes: ['https'],
  host: 'friend-net.herokuapp.com',
  tags: [ // by default: empty Array
    {
      name: "Auth",
      description: "登入登出 router"
    },
  ],
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app.js');           // Your project's root file
});

